#%RAML 1.0 DataType

type: object
properties:
  FlightCode:
    type: string
    required: true
  AirlineName:
    type: string
    required: true
  DepartureAirport:
    type: string
    required: true
  DestinationAirport:
    type: string
    required: true
  AircraftType:
    type: string
    required: true
  SeatAvailability:
    type: number
    required: true
  Price:
    type: number
    required: true
  DepartureDate:
    type: string
    required: true
