#HTTP Listener configurations
http:
  host: "0.0.0.0"
  port: "8081"
  basepath: "/api/acme-travel"

# MySQL DB connection properties

mySQL:
  host: "rds-mysql-assessment.ckld9drpn0yb.eu-west-1.rds.amazonaws.com"
  port: "3306"
  dbname: "airlines_sandbox"
  
# MySQL DB Credentials

credentials:
  username: "Mathan"
  password: "Mathan2020"
